version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:5000/api
    networks:
      - hermeos-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000" # Expose to host for Nginx
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/hermeos
      - PORT=5000
      - JWT_SECRET=supersecretkey
      - SUPER_ADMIN_KEY=admin123
    networks:
      - hermeos-network
    command: sh -c "npx prisma push && npx prisma db seed && npm start"

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=hermeos
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - hermeos-network

networks:
  hermeos-network:
    driver: bridge

volumes:
  db_data:
